sudo: required

language: ruby

services:
  - docker

script:
  - docker build -t gesbo/chef-solo .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" hub.docker.com
  - docker push gesbo/chef-solo